from . import win32 as win32
from _typeshed import Incomplete

class WinColor:
    BLACK: int
    BLUE: int
    GREEN: int
    CYAN: int
    RED: int
    MAGENTA: int
    YELLOW: int
    GREY: int

class WinStyle:
    NORMAL: int
    BRIGHT: int

class WinTerm:
    def __init__(self) -> None: ...
    def get_attrs(self): ...
    def set_attrs(self, value) -> None: ...
    def reset_all(self, on_stderr: Incomplete | None = None) -> None: ...
    def fore(self, fore: Incomplete | None = None, on_stderr: bool = False) -> None: ...
    def back(self, back: Incomplete | None = None, on_stderr: bool = False) -> None: ...
    def style(self, style: Incomplete | None = None, on_stderr: bool = False) -> None: ...
    def set_console(self, attrs: Incomplete | None = None, on_stderr: bool = False) -> None: ...
    def get_position(self, handle): ...
    def set_cursor_position(self, position: Incomplete | None = None, on_stderr: bool = False) -> None: ...
    def cursor_up(self, num_rows: int = 0, on_stderr: bool = False) -> None: ...
    def erase_data(self, mode: int = 0, on_stderr: bool = False) -> None: ...
