from . import units as units
from .Point import Point as Point
from .Qt import QtCore as QtCore
from .colormap import ColorMap as ColorMap
from _typeshed import Incomplete

GLOBAL_PATH: Incomplete

class ParseError(Exception):
    lineNum: Incomplete
    line: Incomplete
    message: Incomplete
    fileName: Incomplete
    def __init__(self, message, lineNum, line, fileName: Incomplete | None = None) -> None: ...

def writeConfigFile(data, fname) -> None: ...
def readConfigFile(fname, **scope): ...
def appendConfigFile(data, fname) -> None: ...
def genString(data, indent: str = ''): ...
def parseString(lines, start: int = 0, **scope): ...
def measureIndent(s): ...
