from ..Qt import QtWidgets
from .Exporter import Exporter
from _typeshed import Incomplete

__all__ = ['MatplotlibExporter']

class MatplotlibExporter(Exporter):
    Name: str
    windows: Incomplete
    def __init__(self, item) -> None: ...
    def parameters(self) -> None: ...
    def cleanAxes(self, axl) -> None: ...
    def export(self, fileName: Incomplete | None = None) -> None: ...

class MatplotlibWindow(QtWidgets.QMainWindow):
    mpl: Incomplete
    def __init__(self) -> None: ...
    def __getattr__(self, attr): ...
    def closeEvent(self, ev) -> None: ...
