from ..Qt import QtCore as QtCore, QtWidgets as QtWidgets
from _typeshed import Incomplete

class CanvasManager(QtCore.QObject):
    SINGLETON: Incomplete
    sigCanvasListChanged: Incomplete
    canvases: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls): ...
    def registerCanvas(self, canvas, name): ...
    def unregisterCanvas(self, name) -> None: ...
    def listCanvases(self): ...
    def getCanvas(self, name): ...

manager: Incomplete

class CanvasCombo(QtWidgets.QComboBox):
    hostName: Incomplete
    def __init__(self, parent: Incomplete | None = None) -> None: ...
    def updateCanvasList(self) -> None: ...
    def setHostName(self, name) -> None: ...
