from ..Qt import QtWidgets
from ..graphicsItems.ROI import ROI
from _typeshed import Incomplete

__all__ = ['Canvas']

class Canvas(QtWidgets.QWidget):
    sigSelectionChanged: Incomplete
    sigItemTransformChanged: Incomplete
    sigItemTransformChangeFinished: Incomplete
    ui: Incomplete
    view: Incomplete
    itemList: Incomplete
    allowTransforms: Incomplete
    multiSelectBox: Incomplete
    redirect: Incomplete
    items: Incomplete
    grid: Incomplete
    hideBtn: Incomplete
    ctrlSize: int
    sizeApplied: bool
    registeredName: Incomplete
    menu: Incomplete
    def __init__(self, parent: Incomplete | None = None, allowTransforms: bool = True, hideCtrl: bool = False, name: Incomplete | None = None) -> None: ...
    def splitterMoved(self) -> None: ...
    def hideBtnClicked(self) -> None: ...
    def autoRange(self) -> None: ...
    def resizeEvent(self, ev: Incomplete | None = None) -> None: ...
    def updateRedirect(self, *args) -> None: ...
    def redirectItems(self, canvas) -> None: ...
    def reclaimItems(self) -> None: ...
    def treeItemChanged(self, item, col) -> None: ...
    def treeItemSelected(self) -> None: ...
    def selectedItems(self):
        """
        Return list of all selected canvasItems
        """
    def selectItem(self, item) -> None: ...
    def showMultiSelectBox(self) -> None: ...
    def mirrorSelectionClicked(self) -> None: ...
    def reflectSelectionClicked(self) -> None: ...
    def resetTransformsClicked(self) -> None: ...
    def multiSelectBoxChanged(self) -> None: ...
    def multiSelectBoxChangeFinished(self) -> None: ...
    def multiSelectBoxMoved(self) -> None: ...
    def addGraphicsItem(self, item, **opts):
        """Add a new GraphicsItem to the scene at pos.
        Common options are name, pos, scale, and z
        """
    def addGroup(self, name, **kargs): ...
    def addItem(self, citem):
        """
        Add an item to the canvas. 
        """
    def treeItemMoved(self, item, parent, index) -> None: ...
    def itemVisibilityChanged(self, item) -> None: ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def addToScene(self, item) -> None: ...
    def removeFromScene(self, item) -> None: ...
    def listItems(self):
        """Return a dictionary of name:item pairs"""
    def getListItem(self, name): ...
    def itemTransformChanged(self, item) -> None: ...
    def itemTransformChangeFinished(self, item) -> None: ...
    menuItem: Incomplete
    def itemListContextMenuEvent(self, ev) -> None: ...
    def removeClicked(self) -> None: ...

class SelectBox(ROI):
    def __init__(self, scalable: bool = False) -> None: ...
