from ..Qt import QtWidgets
from _typeshed import Incomplete

__all__ = ['DockDrop']

class DockDrop:
    """Provides dock-dropping methods"""
    dndWidget: Incomplete
    allowedAreas: Incomplete
    dropArea: Incomplete
    overlay: Incomplete
    def __init__(self, dndWidget) -> None: ...
    def addAllowedArea(self, area) -> None: ...
    def removeAllowedArea(self, area) -> None: ...
    def resizeOverlay(self, size) -> None: ...
    def raiseOverlay(self) -> None: ...
    def dragEnterEvent(self, ev) -> None: ...
    def dragMoveEvent(self, ev) -> None: ...
    def dragLeaveEvent(self, ev) -> None: ...
    def dropEvent(self, ev) -> None: ...

class DropAreaOverlay(QtWidgets.QWidget):
    """Overlay widget that draws drop areas during a drag-drop operation"""
    dropArea: Incomplete
    def __init__(self, parent) -> None: ...
    def setDropArea(self, area) -> None: ...
    def paintEvent(self, ev) -> None: ...
