from ..Qt import QtWidgets
from _typeshed import Incomplete

__all__ = ['GroupBox']

class GroupBox(QtWidgets.QGroupBox):
    """Subclass of QGroupBox that implements collapse handle.
    """
    sigCollapseChanged: Incomplete
    closePath: Incomplete
    openPath: Incomplete
    collapseBtn: Incomplete
    def __init__(self, *args) -> None: ...
    def toggleCollapsed(self) -> None: ...
    def collapsed(self): ...
    def setCollapsed(self, c) -> None: ...
    def setSizePolicy(self, *args, **kwds) -> None: ...
    def setHorizontalPolicy(self, *args) -> None: ...
    def setVerticalPolicy(self, *args) -> None: ...
    def setTitle(self, title) -> None: ...
    def widgetGroupInterface(self): ...
