from ..graphicsItems.PlotItem import PlotItem
from .GraphicsView import GraphicsView
from _typeshed import Incomplete

__all__ = ['PlotWidget']

class PlotWidget(GraphicsView):
    sigRangeChanged: Incomplete
    sigTransformChanged: Incomplete
    plotItem: Incomplete
    def __init__(self, parent: Incomplete | None = None, background: str = 'default', plotItem: Incomplete | None = None, **kargs) -> None: ...
    def close(self) -> None: ...
    def __getattr__(self, attr): ...
    def viewRangeChanged(self, view, range) -> None: ...
    def widgetGroupInterface(self): ...
    def saveState(self): ...
    def restoreState(self, state): ...
    def getPlotItem(self) -> PlotItem:
        """Return the PlotItem contained within."""
