from ..Qt import QtCore as QtCore, QtWidgets as QtWidgets
from ..graphicsItems.PlotItem import PlotItem as PlotItem
from ..graphicsItems.ViewBox import ViewBox as ViewBox
from _typeshed import Incomplete

class FormatExportListWidgetItem(QtWidgets.QListWidgetItem):
    expClass: Incomplete
    def __init__(self, expClass, *args, **kwargs) -> None: ...

class ExportDialog(QtWidgets.QWidget):
    shown: bool
    currentExporter: Incomplete
    scene: Incomplete
    selectBox: Incomplete
    ui: Incomplete
    def __init__(self, scene) -> None: ...
    def show(self, item: Incomplete | None = None) -> None: ...
    def updateItemList(self, select: Incomplete | None = None) -> None: ...
    def updateItemTree(self, item, treeItem, select: Incomplete | None = None) -> None: ...
    def exportItemChanged(self, item, prev) -> None: ...
    def updateFormatList(self) -> None: ...
    def exportFormatChanged(self, item, prev) -> None: ...
    def exportClicked(self) -> None: ...
    def copyClicked(self) -> None: ...
    def close(self) -> None: ...
    def closeEvent(self, event) -> None: ...
