from pyqtgraph.parametertree import Parameter as Parameter
from pyqtgraph.parametertree.Parameter import PARAM_TYPES as PARAM_TYPES
from pyqtgraph.parametertree.parameterTypes import GroupParameter as GroupParameter

def makeChild(chType, cfgDict): ...
def makeMetaChild(name, cfgDict): ...
def makeAllParamTypes(): ...
