from _typeshed import Incomplete
from pyqtgraph.Qt import QtWidgets as QtWidgets
from pyqtgraph.parametertree import InteractiveFunction as InteractiveFunction, Interactor as Interactor, Parameter as Parameter, ParameterTree as ParameterTree, RunOptions as RunOptions

app: Incomplete

class LAST_RESULT:
    """Just for testing purposes"""
    value: Incomplete

def printResult(func): ...

host: Incomplete
interactor: Incomplete

def easySample(a: int = 5, b: int = 6): ...
def stringParams(a: str = '5', b: str = '6'): ...
def requiredParam(a, b: int = 10): ...
def ignoredAParam(a: int = 10, b: int = 20): ...
def runOnButton(a: int = 10, b: int = 20): ...

x: int

def accessVarInDifferentScope(x, y: int = 10): ...

func_interactive: Incomplete

def capslocknames(a: int = 5): ...
def runOnBtnOrChange_listOpts(a: int = 5): ...
def onlyTheArgumentsAppear(thisIsAFunctionArg: bool = True): ...

tree: Incomplete
