import ctypes
from _typeshed import Incomplete

__all__ = ['get_qpainterpath_element_array']

class QArrayDataQt5(ctypes.Structure): ...
class QPainterPathPrivateQt5(ctypes.Structure): ...
class QArrayDataQt6(ctypes.Structure): ...
class QPainterPathPrivateQt6(ctypes.Structure): ...

def get_qpainterpath_element_array(qpath, nelems: Incomplete | None = None): ...

class PrimitiveArray:
    use_sip_array: bool
    use_ptr_to_array: bool
    def __init__(self, Klass, nfields, *, use_array: Incomplete | None = None) -> None: ...
    def resize(self, size) -> None: ...
    def __len__(self) -> int: ...
    def ndarray(self): ...
    def instances(self): ...
    def drawargs(self): ...
